import type { ChangeType, TransmissionCase } from "../../domain/index";
import { canAdvanceTransition, transitionChanges } from "../progress";
import { changeNames, labels, mediumNames } from "./shared";

export function Compare({ item, transition, resolvedIds, segments, evidence, changeType, feedback, onSegment, onEvidence, onType, onCheck, onNext }: { item: TransmissionCase; transition: number; resolvedIds: string[]; segments: string[]; evidence: string[]; changeType: ChangeType; feedback: string; onSegment: (id: string) => void; onEvidence: (id: string) => void; onType: (type: ChangeType) => void; onCheck: () => boolean; onNext: () => void }) {
  const from = item.stages[transition], to = item.stages[transition + 1];
  const expected = transitionChanges(item, transition);
  const resolved = new Set(resolvedIds);
  const canAdvance = canAdvanceTransition(item, transition, resolvedIds);
  const feedbackRef = useRef<HTMLParagraphElement>(null);
  const check = () => { if (!onCheck()) feedbackRef.current?.focus(); };
  return <section className="card compare"><p className="eyebrow">인접 단계 비교 · {transition + 1}/{item.stages.length - 1}</p><h1>바로 다음 전달문만 비교해요</h1><p className="muted">빠짐은 <strong>이전</strong> 문장에서 사라진 조각을, 다른 변화는 <strong>다음</strong> 문장의 조각을 고릅니다.</p><ol className="activity-steps" aria-label="비교 활동 순서"><li><b>1.</b> 표현 조각 고르기</li><li><b>2.</b> 변화 종류 고르기</li><li><b>3.</b> 근거 뜻 고르기</li></ol><div className="compare-layout"><div className="comparison"><MessageCard title={`이전 · ${mediumNames[from.medium]} · 빠짐 찾기`} stage={from} selectable selected={segments} onSelect={onSegment} /><MessageCard title={`다음 · ${mediumNames[to.medium]} · 변화 찾기`} stage={to} selectable selected={segments} onSelect={onSegment} /></div><aside className="meaning-reference"><h2>뜻 장부</h2>{item.meaningUnits.map((unit) => <p key={unit.id}><b>{labels[unit.kind]}</b> {unit.canonicalMeaning}</p>)}</aside></div><aside className="progress-checklist" aria-live="polite"><strong>찾은 변화 {expected.filter((change) => resolved.has(change.id)).length}/{expected.length}</strong><ul>{expected.map((change) => <li key={change.id}>{resolved.has(change.id) ? "✓ 확인함" : "○ 아직 확인"} · {changeNames[change.type]}</li>)}</ul></aside><fieldset><legend>1. 표현 조각 고르기</legend><p className="muted">어느 문장에서든 관련 표현 조각을 누르세요. 선택한 조각: {segments.length ? `${segments.length}개` : "아직 없음"}</p></fieldset><fieldset><legend>2. 변화 종류 고르기</legend><div className="choice-row">{(["omission", "unsupported-addition", "meaning-shift", "meaning-preserving"] as ChangeType[]).map((type) => <label key={type}><input type="radio" name="change-type" checked={changeType === type} onChange={() => onType(type)} />{changeNames[type]}</label>)}</div></fieldset><fieldset><legend>3. 근거 뜻 고르기</legend><div className="check-grid">{item.meaningUnits.map((unit) => <label key={unit.id}><input type="checkbox" checked={evidence.includes(unit.id)} onChange={() => onEvidence(unit.id)} />{labels[unit.kind]} · {unit.canonicalMeaning}</label>)}</div></fieldset><div className="button-row"><button className="primary" onClick={check}>판정 확인</button><button disabled={!canAdvance} onClick={onNext}>{transition + 2 < item.stages.length ? "다음 비교" : "전체 사슬 점검"}</button></div><p ref={feedbackRef} tabIndex={-1} className="feedback" aria-live="polite">{feedback}</p></section>;
}

export function MessageCard({ title, stage, selectable = false, selected = [], onSelect }: { title: string; stage: TransmissionCase["stages"][number]; selectable?: boolean; selected?: string[]; onSelect?: (id: string) => void }) {
  return <article className="message-card"><h2>{title}</h2><p>{stage.senderRole} → {stage.audienceRole}</p><div>{stage.segments.map((segment) => selectable ? <button key={segment.id} className={selected.includes(segment.id) ? "phrase pressed" : "phrase"} aria-pressed={selected.includes(segment.id)} aria-label={segment.accessibilityLabel} onClick={() => onSelect?.(segment.id)}>{segment.text}</button> : <p key={segment.id} className="message-text">{segment.text}</p>)}</div></article>;
}
import { useRef } from "react";
