import { useRef } from "react";
import type { ChangeType, TransmissionCase } from "../../domain/index";
import { canAdvanceTransition, transitionChanges } from "../progress";
import { SelectionSummary } from "./SelectionSummary";
import { changeNames, labels, mediumNames } from "./shared";

export function Compare({ item, transition, resolvedIds, segments, evidence, changeType, feedback, onSegment, onEvidence, onType, onCheck, onClear, onBack, onNext }: { item: TransmissionCase; transition: number; resolvedIds: string[]; segments: string[]; evidence: string[]; changeType: ChangeType; feedback: string; onSegment: (id: string) => void; onEvidence: (id: string) => void; onType: (type: ChangeType) => void; onCheck: () => boolean; onClear: () => void; onBack: () => void; onNext: () => void }) {
  const from = item.stages[transition], to = item.stages[transition + 1];
  const expected = transitionChanges(item, transition);
  const resolved = new Set(resolvedIds);
  const canAdvance = canAdvanceTransition(item, transition, resolvedIds);
  const nextGuidanceId = "compare-next-guidance";
  const feedbackRef = useRef<HTMLParagraphElement>(null);
  const check = () => { if (!onCheck()) feedbackRef.current?.focus(); };
  const guidance = expected.some((change) => change.type === "omission") ? "이전 문장에서 사라진 말을 골라요." : "다음 문장에서 달라지거나 새로 생긴 말을 골라요.";
  return <section className="card compare"><p className="eyebrow">문장 비교 · {transition + 1}/{item.stages.length - 1}</p><h1>바로 다음 전달문을 비교해요</h1><p className="muted">{guidance}</p><ol className="activity-steps" aria-label="비교 활동 순서"><li><b>1.</b> 달라진 말 고르기</li><li><b>2.</b> 어떻게 달라졌나요?</li><li><b>3.</b> 왜 그렇게 생각했나요?</li></ol><div className="compare-layout"><div className="comparison"><MessageCard title={`이전 · ${mediumNames[from.medium]}`} stage={from} selectable selected={segments} onSelect={onSegment} /><MessageCard title={`다음 · ${mediumNames[to.medium]}`} stage={to} selectable selected={segments} onSelect={onSegment} /></div><aside className="meaning-reference"><h2>뜻 장부</h2>{item.meaningUnits.map((unit) => <p key={unit.id}><b>{labels[unit.kind]}</b> {unit.canonicalMeaning}</p>)}</aside></div><aside className="progress-checklist" aria-live="polite"><strong>찾은 변화 {expected.filter((change) => resolved.has(change.id)).length}/{expected.length}</strong><ul>{expected.map((change) => <li key={change.id}>{resolved.has(change.id) ? "✓ 확인함" : "○ 아직 확인"} · {changeNames[change.type]}</li>)}</ul></aside><fieldset><legend>1. 달라진 말 고르기</legend><p className="muted">{guidance}</p></fieldset><fieldset><legend>2. 어떻게 달라졌나요?</legend><div className="choice-row">{(["omission", "unsupported-addition", "meaning-shift", "meaning-preserving"] as ChangeType[]).map((type) => <label key={type}><input type="radio" name="change-type" checked={changeType === type} onChange={() => onType(type)} />{changeNames[type]}</label>)}</div></fieldset><fieldset><legend>3. 왜 그렇게 생각했나요?</legend><div className="check-grid">{item.meaningUnits.map((unit) => <label key={unit.id}><input type="checkbox" checked={evidence.includes(unit.id)} onChange={() => onEvidence(unit.id)} />{labels[unit.kind]} · {unit.canonicalMeaning}</label>)}</div></fieldset><SelectionSummary selectedSegmentCount={segments.length} selectedEvidenceCount={evidence.length} onClear={onClear} guidanceId={nextGuidanceId} showNextGuidance={!canAdvance} /><div className="button-row"><button className="primary" onClick={check}>내 답 확인</button><button disabled={!canAdvance} aria-describedby={!canAdvance ? nextGuidanceId : undefined} onClick={onNext}>{transition + 2 < item.stages.length ? "다음 비교" : "처음부터 끝까지 보기"}</button></div><p ref={feedbackRef} tabIndex={-1} className="feedback" aria-live="polite">{feedback}</p><div className="back-row"><button className="text-button" onClick={onBack}>사건 설명으로</button></div></section>;
}

export function MessageCard({ title, stage, selectable = false, selected = [], onSelect }: { title: string; stage: TransmissionCase["stages"][number]; selectable?: boolean; selected?: string[]; onSelect?: (id: string) => void }) {
  return <article className="message-card"><h2>{title}</h2><p>{stage.senderRole} → {stage.audienceRole}</p><div>{stage.segments.map((segment) => selectable ? <button key={segment.id} className={selected.includes(segment.id) ? "phrase pressed" : "phrase"} aria-pressed={selected.includes(segment.id)} aria-label={segment.accessibilityLabel} onClick={() => onSelect?.(segment.id)}>{segment.text}</button> : <p key={segment.id} className="message-text">{segment.text}</p>)}</div></article>;
}
